// Seed script for ToolForge AI - Populate database with real AI tools
// Run with: tsx scripts/seed-tools.ts

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Comprehensive AI Tools Database
const tools = [
  // WRITING TOOLS (15)
  {
    slug: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'Conversational AI for text generation and assistance',
    description: 'OpenAI\'s ChatGPT is a powerful conversational AI that can help with writing, coding, analysis, and creative tasks. Powered by GPT-4, it offers natural language understanding and generation.',
    category: 'writing',
    website_url: 'https://chat.openai.com',
    affiliate_link: 'https://toolforge.ai/go/chatgpt',
    logo_url: 'https://cdn.brandfetch.io/openai.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$20/month',
    features: ['GPT-4 access', 'Unlimited messages', 'Advanced reasoning', 'Code interpreter', 'Image generation'],
    tags: ['AI writing', 'chatbot', 'GPT-4', 'content creation', 'productivity'],
    rating: 4.8,
    review_count: 15420,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'jasper-ai',
    name: 'Jasper AI',
    tagline: 'AI copilot for enterprise marketing teams',
    description: 'Jasper is an AI writing assistant specifically designed for marketing teams. It helps create high-quality content, from blog posts to social media, with brand voice consistency.',
    category: 'writing',
    website_url: 'https://www.jasper.ai',
    affiliate_link: 'https://toolforge.ai/go/jasper-ai',
    logo_url: 'https://cdn.brandfetch.io/jasper.ai/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$49/month',
    features: ['Brand voice training', 'SEO optimization', 'Team collaboration', 'Multiple templates', 'Plagiarism checker'],
    tags: ['content marketing', 'copywriting', 'SEO', 'brand voice', 'team collaboration'],
    rating: 4.7,
    review_count: 8543,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'copy-ai',
    name: 'Copy.ai',
    tagline: 'AI-powered copywriting for marketing teams',
    description: 'Copy.ai helps marketers and businesses create compelling copy in seconds. From product descriptions to ad copy, it provides templates and AI assistance for all marketing needs.',
    category: 'writing',
    website_url: 'https://www.copy.ai',
    affiliate_link: 'https://toolforge.ai/go/copy-ai',
    logo_url: 'https://cdn.brandfetch.io/copy.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$36/month',
    features: ['90+ copywriting templates', 'Brand voice', 'Multilingual support', 'Team collaboration', 'Chrome extension'],
    tags: ['copywriting', 'marketing', 'ad copy', 'social media', 'email'],
    rating: 4.5,
    review_count: 6234,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'writesonic',
    name: 'Writesonic',
    tagline: 'AI writer with built-in SEO optimizer',
    description: 'Writesonic combines AI writing with SEO optimization, helping you create content that ranks. Features include article writing, product descriptions, and ad copy generation.',
    category: 'writing',
    website_url: 'https://writesonic.com',
    affiliate_link: 'https://toolforge.ai/go/writesonic',
    logo_url: 'https://cdn.brandfetch.io/writesonic.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$16/month',
    features: ['SEO article writer', 'AI article writer 5.0', 'Fact-checked content', 'Bulk generation', 'API access'],
    tags: ['SEO writing', 'blog posts', 'product descriptions', 'landing pages'],
    rating: 4.6,
    review_count: 5432,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'rytr',
    name: 'Rytr',
    tagline: 'Affordable AI writing assistant',
    description: 'Rytr is a cost-effective AI writing tool that helps create quality content quickly. Perfect for individuals and small businesses looking for budget-friendly AI writing.',
    category: 'writing',
    website_url: 'https://rytr.me',
    affiliate_link: 'https://toolforge.ai/go/rytr',
    logo_url: 'https://cdn.brandfetch.io/rytr.me/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9/month',
    features: ['40+ use cases', '30+ languages', 'Tone selection', 'Plagiarism checker', 'Chrome extension'],
    tags: ['budget friendly', 'content writing', 'multilingual', 'copywriting'],
    rating: 4.4,
    review_count: 4123,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'quillbot',
    name: 'QuillBot',
    tagline: 'AI-powered paraphrasing and writing enhancement',
    description: 'QuillBot specializes in paraphrasing, grammar checking, and text summarization. Perfect for students, writers, and professionals who need to refine their writing.',
    category: 'writing',
    website_url: 'https://quillbot.com',
    affiliate_link: 'https://toolforge.ai/go/quillbot',
    logo_url: 'https://cdn.brandfetch.io/quillbot.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8.33/month',
    features: ['Paraphraser', 'Grammar checker', 'Summarizer', 'Citation generator', 'Translator'],
    tags: ['paraphrasing', 'grammar', 'summarization', 'academic writing'],
    rating: 4.5,
    review_count: 7234,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'grammarly',
    name: 'Grammarly',
    tagline: 'AI writing assistant for grammar and clarity',
    description: 'Grammarly is the leading AI-powered writing assistant that helps you write clear, mistake-free content. Now includes generative AI features for enhanced writing.',
    category: 'writing',
    website_url: 'https://www.grammarly.com',
    affiliate_link: 'https://toolforge.ai/go/grammarly',
    logo_url: 'https://cdn.brandfetch.io/grammarly.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12/month',
    features: ['Grammar checking', 'Tone detection', 'Plagiarism detection', 'Style suggestions', 'AI writing'],
    tags: ['grammar', 'editing', 'proofreading', 'writing assistant'],
    rating: 4.7,
    review_count: 12543,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'wordtune',
    name: 'Wordtune',
    tagline: 'AI writing companion that understands context',
    description: 'Wordtune helps you rewrite sentences, find better words, and improve your writing style. It understands context and offers intelligent suggestions.',
    category: 'writing',
    website_url: 'https://www.wordtune.com',
    affiliate_link: 'https://toolforge.ai/go/wordtune',
    logo_url: 'https://cdn.brandfetch.io/wordtune.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9.99/month',
    features: ['Rewrite suggestions', 'Tone adjustment', 'Text expansion', 'Summarization', 'AI writing'],
    tags: ['rewriting', 'editing', 'clarity', 'productivity'],
    rating: 4.6,
    review_count: 4567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'notion-ai',
    name: 'Notion AI',
    tagline: 'AI-powered workspace and writing assistant',
    description: 'Notion AI integrates directly into Notion, helping you write, edit, summarize, and brainstorm without leaving your workspace.',
    category: 'writing',
    website_url: 'https://www.notion.so/product/ai',
    affiliate_link: 'https://toolforge.ai/go/notion-ai',
    logo_url: 'https://cdn.brandfetch.io/notion.so/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$10/month',
    features: ['Integrated with Notion', 'Content generation', 'Summarization', 'Translation', 'Action items'],
    tags: ['workspace', 'productivity', 'note-taking', 'collaboration'],
    rating: 4.5,
    review_count: 5678,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'sudowrite',
    name: 'Sudowrite',
    tagline: 'AI writing partner for creative writers',
    description: 'Sudowrite is designed specifically for novelists and screenwriters. It helps with brainstorming, character development, and overcoming writer\'s block.',
    category: 'writing',
    website_url: 'https://www.sudowrite.com',
    affiliate_link: 'https://toolforge.ai/go/sudowrite',
    logo_url: 'https://cdn.brandfetch.io/sudowrite.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$19/month',
    features: ['Story engine', 'Character development', 'Describe mode', 'Brainstorming', 'Rewrite'],
    tags: ['creative writing', 'fiction', 'storytelling', 'novelists'],
    rating: 4.7,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'claude',
    name: 'Claude',
    tagline: 'Anthropic\'s AI assistant for advanced reasoning',
    description: 'Claude is Anthropic\'s AI assistant known for its strong reasoning, analysis, and writing capabilities. Excels at long-form content and complex tasks.',
    category: 'writing',
    website_url: 'https://claude.ai',
    affiliate_link: 'https://toolforge.ai/go/claude',
    logo_url: 'https://cdn.brandfetch.io/anthropic.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$20/month',
    features: ['200K context window', 'Advanced reasoning', 'Code generation', 'Document analysis', 'Vision capabilities'],
    tags: ['AI assistant', 'analysis', 'research', 'coding', 'writing'],
    rating: 4.8,
    review_count: 6789,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'anyword',
    name: 'Anyword',
    tagline: 'AI copywriting with performance prediction',
    description: 'Anyword uses AI to generate marketing copy and predicts its performance before you publish. Ideal for data-driven marketers.',
    category: 'writing',
    website_url: 'https://anyword.com',
    affiliate_link: 'https://toolforge.ai/go/anyword',
    logo_url: 'https://cdn.brandfetch.io/anyword.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$49/month',
    features: ['Performance prediction', 'Brand guidelines', 'Blog wizard', 'Landing page copy', 'A/B testing'],
    tags: ['marketing copy', 'performance analytics', 'conversion optimization'],
    rating: 4.5,
    review_count: 2134,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'simplified',
    name: 'Simplified',
    tagline: 'All-in-one AI content creation platform',
    description: 'Simplified combines AI writing, design, video editing, and social media management in one platform. Perfect for content creators and marketers.',
    category: 'writing',
    website_url: 'https://simplified.com',
    affiliate_link: 'https://toolforge.ai/go/simplified',
    logo_url: 'https://cdn.brandfetch.io/simplified.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12/month',
    features: ['AI writer', 'Design tools', 'Video editor', 'Social media scheduler', 'Brand kit'],
    tags: ['all-in-one', 'content creation', 'social media', 'design'],
    rating: 4.4,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'hypotenuse-ai',
    name: 'Hypotenuse AI',
    tagline: 'AI content writer for ecommerce and marketing',
    description: 'Hypotenuse AI specializes in bulk content generation for ecommerce. Create product descriptions, blog posts, and marketing content at scale.',
    category: 'writing',
    website_url: 'https://www.hypotenuse.ai',
    affiliate_link: 'https://toolforge.ai/go/hypotenuse-ai',
    logo_url: 'https://cdn.brandfetch.io/hypotenuse.ai/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$15/month',
    features: ['Bulk product descriptions', 'SEO articles', 'Image generation', 'Shopify integration', 'API access'],
    tags: ['ecommerce', 'product descriptions', 'bulk content', 'SEO'],
    rating: 4.5,
    review_count: 1876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'frase',
    name: 'Frase',
    tagline: 'AI-powered SEO content optimization',
    description: 'Frase helps you research, write, and optimize SEO content. It analyzes top search results and provides data-driven recommendations.',
    category: 'writing',
    website_url: 'https://www.frase.io',
    affiliate_link: 'https://toolforge.ai/go/frase',
    logo_url: 'https://cdn.brandfetch.io/frase.io/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$14.99/month',
    features: ['SEO research', 'Content optimization', 'SERP analysis', 'AI writing', 'Team collaboration'],
    tags: ['SEO', 'content optimization', 'SERP analysis', 'keyword research'],
    rating: 4.6,
    review_count: 2567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // IMAGE GENERATION TOOLS (15)
  {
    slug: 'midjourney',
    name: 'Midjourney',
    tagline: 'AI art generator with stunning quality',
    description: 'Midjourney is renowned for creating highly artistic and visually stunning AI images. Accessible through Discord, it excels at creative and stylized artwork.',
    category: 'image',
    website_url: 'https://www.midjourney.com',
    affiliate_link: 'https://toolforge.ai/go/midjourney',
    logo_url: 'https://cdn.brandfetch.io/midjourney.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$10/month',
    features: ['High-quality art', 'Multiple aspect ratios', 'Style variations', 'Upscaling', 'Community gallery'],
    tags: ['AI art', 'image generation', 'creative', 'digital art'],
    rating: 4.8,
    review_count: 18543,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'dall-e-3',
    name: 'DALL-E 3',
    tagline: 'OpenAI\'s advanced image generation',
    description: 'DALL-E 3 from OpenAI creates highly accurate images from text descriptions. Integrated with ChatGPT Plus for seamless generation.',
    category: 'image',
    website_url: 'https://openai.com/dall-e-3',
    affiliate_link: 'https://toolforge.ai/go/dall-e-3',
    logo_url: 'https://cdn.brandfetch.io/openai.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$20/month',
    features: ['Text accuracy', 'ChatGPT integration', 'High resolution', 'Multiple styles', 'Commercial use'],
    tags: ['image generation', 'AI art', 'OpenAI', 'text-to-image'],
    rating: 4.7,
    review_count: 12456,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'stable-diffusion',
    name: 'Stable Diffusion',
    tagline: 'Open-source AI image generation',
    description: 'Stable Diffusion is an open-source AI image generator that can run locally. Highly customizable with models and extensions for various art styles.',
    category: 'image',
    website_url: 'https://stability.ai',
    affiliate_link: 'https://toolforge.ai/go/stable-diffusion',
    logo_url: 'https://cdn.brandfetch.io/stability.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: 'Free (self-hosted)',
    features: ['Open source', 'Local generation', 'Custom models', 'ControlNet', 'API access'],
    tags: ['open source', 'customizable', 'self-hosted', 'image generation'],
    rating: 4.6,
    review_count: 9876,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'leonardo-ai',
    name: 'Leonardo.Ai',
    tagline: 'AI art generator for game assets and creative work',
    description: 'Leonardo.Ai is designed for creators and game developers. It offers consistent character generation, fine-tuned models, and creative control.',
    category: 'image',
    website_url: 'https://leonardo.ai',
    affiliate_link: 'https://toolforge.ai/go/leonardo-ai',
    logo_url: 'https://cdn.brandfetch.io/leonardo.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12/month',
    features: ['Character consistency', 'Canvas editor', 'Fine-tuned models', 'Texture generation', '3D assets'],
    tags: ['game assets', 'character design', '3D', 'consistent generation'],
    rating: 4.7,
    review_count: 6543,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'ideogram',
    name: 'Ideogram',
    tagline: 'AI image generator with excellent text rendering',
    description: 'Ideogram excels at rendering text within images, making it perfect for creating posters, logos, and designs with typography.',
    category: 'image',
    website_url: 'https://ideogram.ai',
    affiliate_link: 'https://toolforge.ai/go/ideogram',
    logo_url: 'https://cdn.brandfetch.io/ideogram.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8/month',
    features: ['Text rendering', 'Magic Prompt', 'Multiple styles', 'High quality', 'Fast generation'],
    tags: ['text rendering', 'typography', 'logos', 'posters'],
    rating: 4.6,
    review_count: 4321,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'adobe-firefly',
    name: 'Adobe Firefly',
    tagline: 'Adobe\'s AI image generator for creative workflows',
    description: 'Adobe Firefly integrates AI generation into Adobe\'s creative ecosystem. Designed for commercial use with focus on safety and ethical AI.',
    category: 'image',
    website_url: 'https://www.adobe.com/products/firefly.html',
    affiliate_link: 'https://toolforge.ai/go/adobe-firefly',
    logo_url: 'https://cdn.brandfetch.io/adobe.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: 'Included with Creative Cloud',
    features: ['Adobe integration', 'Generative fill', 'Text effects', 'Recoloring', 'Commercial safe'],
    tags: ['Adobe', 'commercial use', 'creative cloud', 'professional'],
    rating: 4.5,
    review_count: 7654,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'canva-ai',
    name: 'Canva AI',
    tagline: 'AI design and image generation in Canva',
    description: 'Canva\'s AI tools include image generation, background removal, and magic editing. Perfect for non-designers creating professional content.',
    category: 'image',
    website_url: 'https://www.canva.com/ai-image-generator/',
    affiliate_link: 'https://toolforge.ai/go/canva-ai',
    logo_url: 'https://cdn.brandfetch.io/canva.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12.99/month',
    features: ['Text to image', 'Magic eraser', 'Background remover', 'Magic expand', 'Design templates'],
    tags: ['design', 'easy to use', 'templates', 'social media'],
    rating: 4.6,
    review_count: 11234,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'clipdrop',
    name: 'Clipdrop',
    tagline: 'AI-powered image editing and generation',
    description: 'Clipdrop offers a suite of AI image tools including generation, background removal, upscaling, and cleanup. Simple and powerful.',
    category: 'image',
    website_url: 'https://clipdrop.co',
    affiliate_link: 'https://toolforge.ai/go/clipdrop',
    logo_url: 'https://cdn.brandfetch.io/clipdrop.co/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9/month',
    features: ['Image generation', 'Background removal', 'Image upscaling', 'Cleanup', 'Relight'],
    tags: ['image editing', 'background removal', 'upscaling', 'cleanup'],
    rating: 4.5,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'playground-ai',
    name: 'Playground AI',
    tagline: 'Free AI image generator with powerful editing',
    description: 'Playground AI offers generous free credits and advanced editing features. Great for both beginners and professionals.',
    category: 'image',
    website_url: 'https://playgroundai.com',
    affiliate_link: 'https://toolforge.ai/go/playground-ai',
    logo_url: 'https://cdn.brandfetch.io/playgroundai.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$15/month',
    features: ['Canvas editor', 'Multiple models', 'ControlNet', 'Mixing', 'Commercial use'],
    tags: ['free tier', 'editing', 'canvas', 'beginner friendly'],
    rating: 4.5,
    review_count: 5432,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'photosonic',
    name: 'Photosonic',
    tagline: 'AI art generator by Writesonic',
    description: 'Photosonic makes AI art generation simple and accessible. Part of the Writesonic ecosystem for comprehensive content creation.',
    category: 'image',
    website_url: 'https://photosonic.writesonic.com',
    affiliate_link: 'https://toolforge.ai/go/photosonic',
    logo_url: 'https://cdn.brandfetch.io/writesonic.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$16/month',
    features: ['Simple interface', 'Multiple styles', 'Quick generation', 'High quality', 'API access'],
    tags: ['simple', 'beginner friendly', 'fast', 'Writesonic'],
    rating: 4.4,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'bluewillow',
    name: 'BlueWillow',
    tagline: 'Free AI image generator on Discord',
    description: 'BlueWillow is a free alternative to Midjourney, accessible through Discord. Create unlimited images with a supportive community.',
    category: 'image',
    website_url: 'https://www.bluewillow.ai',
    affiliate_link: 'https://toolforge.ai/go/bluewillow',
    logo_url: 'https://cdn.brandfetch.io/bluewillow.ai/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Unlimited generation', 'Discord based', 'Multiple styles', 'Community support', 'No subscription'],
    tags: ['free', 'Discord', 'unlimited', 'community'],
    rating: 4.3,
    review_count: 4567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'getimg-ai',
    name: 'Getimg.ai',
    tagline: 'Suite of AI image generation tools',
    description: 'Getimg.ai offers text-to-image, image editing, and custom AI model training. Comprehensive platform for image generation needs.',
    category: 'image',
    website_url: 'https://getimg.ai',
    affiliate_link: 'https://toolforge.ai/go/getimg-ai',
    logo_url: 'https://cdn.brandfetch.io/getimg.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12/month',
    features: ['Text to image', 'Image editor', 'DreamBooth', 'API access', 'Custom models'],
    tags: ['image editing', 'custom models', 'API', 'versatile'],
    rating: 4.5,
    review_count: 2876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'craiyon',
    name: 'Craiyon',
    tagline: 'Free AI image generator (formerly DALL-E mini)',
    description: 'Craiyon, previously known as DALL-E mini, offers free AI image generation. Simple interface perfect for casual users and experimentation.',
    category: 'image',
    website_url: 'https://www.craiyon.com',
    affiliate_link: 'https://toolforge.ai/go/craiyon',
    logo_url: 'https://cdn.brandfetch.io/craiyon.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$6/month',
    features: ['Free generation', 'Simple interface', 'No signup required', 'Multiple images', 'Fast generation'],
    tags: ['free', 'simple', 'no signup', 'beginner friendly'],
    rating: 4.2,
    review_count: 6789,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'nightcafe',
    name: 'NightCafe',
    tagline: 'AI art generator with community features',
    description: 'NightCafe combines AI art generation with social features. Daily free credits, challenges, and a vibrant community of artists.',
    category: 'image',
    website_url: 'https://nightcafe.studio',
    affiliate_link: 'https://toolforge.ai/go/nightcafe',
    logo_url: 'https://cdn.brandfetch.io/nightcafe.studio/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$5.99/month',
    features: ['Multiple algorithms', 'Daily free credits', 'Community challenges', 'Print shop', 'Video generation'],
    tags: ['community', 'social', 'challenges', 'multiple styles'],
    rating: 4.5,
    review_count: 5234,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'artbreeder',
    name: 'Artbreeder',
    tagline: 'Collaborative AI art platform',
    description: 'Artbreeder lets you create and remix AI images through breeding and mixing. Unique approach to AI art with focus on iteration and evolution.',
    category: 'image',
    website_url: 'https://www.artbreeder.com',
    affiliate_link: 'https://toolforge.ai/go/artbreeder',
    logo_url: 'https://cdn.brandfetch.io/artbreeder.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8.99/month',
    features: ['Image breeding', 'Character creation', 'Landscape generation', 'Mixing', 'Community gallery'],
    tags: ['collaborative', 'breeding', 'character design', 'portraits'],
    rating: 4.4,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // VIDEO TOOLS (10)
  {
    slug: 'runway',
    name: 'Runway',
    tagline: 'AI-powered video editing and generation',
    description: 'Runway offers cutting-edge AI video tools including Gen-2 for text-to-video, motion tracking, and advanced editing capabilities.',
    category: 'video',
    website_url: 'https://runwayml.com',
    affiliate_link: 'https://toolforge.ai/go/runway',
    logo_url: 'https://cdn.brandfetch.io/runwayml.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$15/month',
    features: ['Gen-2 video generation', 'Motion tracking', 'Green screen', 'Frame interpolation', 'AI magic tools'],
    tags: ['video generation', 'AI video', 'video editing', 'text-to-video'],
    rating: 4.7,
    review_count: 5678,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'pika',
    name: 'Pika',
    tagline: 'AI video generator from text and images',
    description: 'Pika creates videos from text prompts and images. Known for its ease of use and high-quality video generation.',
    category: 'video',
    website_url: 'https://pika.art',
    affiliate_link: 'https://toolforge.ai/go/pika',
    logo_url: 'https://cdn.brandfetch.io/pika.art/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$10/month',
    features: ['Text to video', 'Image to video', 'Video extension', 'Camera controls', 'High quality'],
    tags: ['video generation', 'text-to-video', 'image-to-video', 'creative'],
    rating: 4.6,
    review_count: 4321,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'synthesia',
    name: 'Synthesia',
    tagline: 'AI video creation with digital avatars',
    description: 'Synthesia creates professional videos with AI avatars. Perfect for training videos, presentations, and content without filming.',
    category: 'video',
    website_url: 'https://www.synthesia.io',
    affiliate_link: 'https://toolforge.ai/go/synthesia',
    logo_url: 'https://cdn.brandfetch.io/synthesia.io/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$22/month',
    features: ['AI avatars', '120+ languages', 'Custom avatars', 'Templates', 'Screen recording'],
    tags: ['AI avatars', 'video creation', 'multilingual', 'training videos'],
    rating: 4.6,
    review_count: 3456,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'heygen',
    name: 'HeyGen',
    tagline: 'Create videos with AI avatars instantly',
    description: 'HeyGen makes it easy to create talking avatar videos. Great for marketing, education, and social media with realistic AI presenters.',
    category: 'video',
    website_url: 'https://www.heygen.com',
    affiliate_link: 'https://toolforge.ai/go/heygen',
    logo_url: 'https://cdn.brandfetch.io/heygen.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$29/month',
    features: ['Avatar videos', 'Voice cloning', '40+ languages', 'Custom avatars', 'Video templates'],
    tags: ['avatars', 'talking head', 'voice cloning', 'marketing'],
    rating: 4.5,
    review_count: 4567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'descript',
    name: 'Descript',
    tagline: 'All-in-one video and podcast editing',
    description: 'Descript offers text-based video editing, transcription, screen recording, and AI voices. Edit videos as easily as documents.',
    category: 'video',
    website_url: 'https://www.descript.com',
    affiliate_link: 'https://toolforge.ai/go/descript',
    logo_url: 'https://cdn.brandfetch.io/descript.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12/month',
    features: ['Text-based editing', 'Transcription', 'Screen recording', 'AI voices', 'Overdub'],
    tags: ['video editing', 'podcasting', 'transcription', 'screen recording'],
    rating: 4.7,
    review_count: 7654,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'opus-clip',
    name: 'Opus Clip',
    tagline: 'AI-powered video repurposing',
    description: 'Opus Clip automatically turns long videos into viral short clips. AI identifies the best moments and creates social-ready content.',
    category: 'video',
    website_url: 'https://www.opus.pro',
    affiliate_link: 'https://toolforge.ai/go/opus-clip',
    logo_url: 'https://cdn.brandfetch.io/opus.pro/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9/month',
    features: ['Auto clip generation', 'Viral score', 'Auto captions', 'Brand templates', 'Multi-platform'],
    tags: ['video repurposing', 'short form', 'social media', 'clips'],
    rating: 4.6,
    review_count: 3234,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'pictory',
    name: 'Pictory',
    tagline: 'Transform content into engaging videos',
    description: 'Pictory turns scripts, blog posts, and long videos into short, branded videos. Perfect for content marketers and creators.',
    category: 'video',
    website_url: 'https://pictory.ai',
    affiliate_link: 'https://toolforge.ai/go/pictory',
    logo_url: 'https://cdn.brandfetch.io/pictory.ai/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$23/month',
    features: ['Script to video', 'Blog to video', 'Auto captions', 'Video highlights', 'Stock library'],
    tags: ['content repurposing', 'blog to video', 'marketing', 'social media'],
    rating: 4.5,
    review_count: 2876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'invideo-ai',
    name: 'InVideo AI',
    tagline: 'AI video generator from text prompts',
    description: 'InVideo AI creates complete videos from text prompts. Just describe your video and AI handles scripting, visuals, and voiceover.',
    category: 'video',
    website_url: 'https://invideo.io/ai',
    affiliate_link: 'https://toolforge.ai/go/invideo-ai',
    logo_url: 'https://cdn.brandfetch.io/invideo.io/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$20/month',
    features: ['Text to video', 'AI voiceover', 'Stock media', 'Templates', 'Brand customization'],
    tags: ['text-to-video', 'automated', 'marketing', 'social media'],
    rating: 4.5,
    review_count: 4123,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'fliki',
    name: 'Fliki',
    tagline: 'Text to video and speech with AI',
    description: 'Fliki converts text into videos with lifelike voiceovers. Great for creating video content quickly from blog posts or scripts.',
    category: 'video',
    website_url: 'https://fliki.ai',
    affiliate_link: 'https://toolforge.ai/go/fliki',
    logo_url: 'https://cdn.brandfetch.io/fliki.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8/month',
    features: ['Text to video', 'AI voices', 'Multi-language', 'Stock media', 'Video templates'],
    tags: ['text-to-speech', 'text-to-video', 'voiceover', 'content creation'],
    rating: 4.4,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'lumen5',
    name: 'Lumen5',
    tagline: 'Video creation platform for marketers',
    description: 'Lumen5 helps marketers create engaging video content from blog posts and content. AI-powered with extensive customization options.',
    category: 'video',
    website_url: 'https://lumen5.com',
    affiliate_link: 'https://toolforge.ai/go/lumen5',
    logo_url: 'https://cdn.brandfetch.io/lumen5.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$19/month',
    features: ['Blog to video', 'Video templates', 'Media library', 'Brand kit', 'Social formats'],
    tags: ['marketing', 'blog to video', 'social media', 'brand content'],
    rating: 4.4,
    review_count: 4567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // CODE TOOLS (10)
  {
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    tagline: 'AI pair programmer from GitHub and OpenAI',
    description: 'GitHub Copilot is your AI coding assistant. It suggests code completions, entire functions, and helps you write code faster.',
    category: 'code',
    website_url: 'https://github.com/features/copilot',
    affiliate_link: 'https://toolforge.ai/go/github-copilot',
    logo_url: 'https://cdn.brandfetch.io/github.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$10/month',
    features: ['Code completion', 'Multi-language', 'IDE integration', 'Chat interface', 'Documentation'],
    tags: ['code assistant', 'GitHub', 'OpenAI', 'IDE', 'productivity'],
    rating: 4.7,
    review_count: 23456,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'cursor',
    name: 'Cursor',
    tagline: 'AI-first code editor',
    description: 'Cursor is an AI-native code editor built on VS Code. Chat with your codebase, generate code, and refactor with AI assistance.',
    category: 'code',
    website_url: 'https://cursor.sh',
    affiliate_link: 'https://toolforge.ai/go/cursor',
    logo_url: 'https://cdn.brandfetch.io/cursor.sh/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$20/month',
    features: ['Codebase chat', 'Multi-file editing', 'AI generation', 'VS Code compatible', 'Privacy mode'],
    tags: ['code editor', 'AI coding', 'VS Code', 'codebase chat'],
    rating: 4.8,
    review_count: 8765,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'codeium',
    name: 'Codeium',
    tagline: 'Free AI code completion',
    description: 'Codeium offers AI code completion for free across 70+ languages. Fast, accurate suggestions with privacy-focused approach.',
    category: 'code',
    website_url: 'https://codeium.com',
    affiliate_link: 'https://toolforge.ai/go/codeium',
    logo_url: 'https://cdn.brandfetch.io/codeium.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: 'Free',
    features: ['70+ languages', 'IDE integration', 'Fast suggestions', 'Context aware', 'Free tier'],
    tags: ['free', 'code completion', 'multi-language', 'privacy'],
    rating: 4.6,
    review_count: 5432,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'tabnine',
    name: 'Tabnine',
    tagline: 'AI code assistant for teams',
    description: 'Tabnine provides AI code completions trained on your code. Offers on-premise deployment for enterprise security.',
    category: 'code',
    website_url: 'https://www.tabnine.com',
    affiliate_link: 'https://toolforge.ai/go/tabnine',
    logo_url: 'https://cdn.brandfetch.io/tabnine.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12/month',
    features: ['Code completion', 'Team training', 'On-premise', 'IDE plugins', 'Privacy focused'],
    tags: ['code completion', 'enterprise', 'privacy', 'team'],
    rating: 4.5,
    review_count: 6543,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'amazon-codewhisperer',
    name: 'Amazon CodeWhisperer',
    tagline: 'AI coding companion from AWS',
    description: 'Amazon CodeWhisperer provides code suggestions optimized for AWS APIs. Free for individual use with security scans.',
    category: 'code',
    website_url: 'https://aws.amazon.com/codewhisperer/',
    affiliate_link: 'https://toolforge.ai/go/amazon-codewhisperer',
    logo_url: 'https://cdn.brandfetch.io/aws.amazon.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: 'Free',
    features: ['AWS optimized', 'Security scans', 'Reference tracking', 'Multi-language', 'IDE integration'],
    tags: ['AWS', 'free', 'security', 'cloud development'],
    rating: 4.4,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'replit-ghostwriter',
    name: 'Replit Ghostwriter',
    tagline: 'AI pair programmer in Replit',
    description: 'Ghostwriter is Replit\'s AI coding assistant. Code, debug, and learn directly in your browser with AI help.',
    category: 'code',
    website_url: 'https://replit.com/ai',
    affiliate_link: 'https://toolforge.ai/go/replit-ghostwriter',
    logo_url: 'https://cdn.brandfetch.io/replit.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$10/month',
    features: ['Code completion', 'Chat', 'Debugging', 'Explanation', 'Browser based'],
    tags: ['browser IDE', 'code completion', 'learning', 'collaboration'],
    rating: 4.5,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    tagline: 'AI coding assistant that knows your codebase',
    description: 'Cody understands your entire codebase to provide contextual answers and code suggestions. Enterprise-grade with security.',
    category: 'code',
    website_url: 'https://sourcegraph.com/cody',
    affiliate_link: 'https://toolforge.ai/go/sourcegraph-cody',
    logo_url: 'https://cdn.brandfetch.io/sourcegraph.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: 'Free',
    features: ['Codebase context', 'Code generation', 'Refactoring', 'Security', 'Enterprise'],
    tags: ['codebase chat', 'enterprise', 'security', 'refactoring'],
    rating: 4.6,
    review_count: 1876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'phind',
    name: 'Phind',
    tagline: 'AI search engine for developers',
    description: 'Phind is an AI-powered search engine optimized for developers. Get instant answers to coding questions with sources.',
    category: 'code',
    website_url: 'https://www.phind.com',
    affiliate_link: 'https://toolforge.ai/go/phind',
    logo_url: 'https://cdn.brandfetch.io/phind.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$15/month',
    features: ['AI search', 'Code examples', 'Multiple sources', 'VS Code extension', 'Fast responses'],
    tags: ['developer search', 'code help', 'documentation', 'learning'],
    rating: 4.6,
    review_count: 4321,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'blackbox-ai',
    name: 'Blackbox AI',
    tagline: 'AI code generator and autocomplete',
    description: 'Blackbox AI provides code generation, autocomplete, and a chat interface for coding help. Works across multiple languages.',
    category: 'code',
    website_url: 'https://www.blackbox.ai',
    affiliate_link: 'https://toolforge.ai/go/blackbox-ai',
    logo_url: 'https://cdn.brandfetch.io/blackbox.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$0.99/month',
    features: ['Code generation', 'Autocomplete', 'Chat', 'Multi-language', 'Chrome extension'],
    tags: ['code generation', 'autocomplete', 'affordable', 'browser extension'],
    rating: 4.3,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'aider',
    name: 'Aider',
    tagline: 'AI pair programming in your terminal',
    description: 'Aider is a command-line AI coding assistant that can edit code in your local git repo. Works with Claude, GPT-4, and more.',
    category: 'code',
    website_url: 'https://aider.chat',
    affiliate_link: 'https://toolforge.ai/go/aider',
    logo_url: 'https://cdn.brandfetch.io/aider.chat/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free (BYOK)',
    features: ['Terminal based', 'Git integration', 'Multiple models', 'Open source', 'Local files'],
    tags: ['terminal', 'open source', 'git', 'command line'],
    rating: 4.7,
    review_count: 1234,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // CHAT TOOLS (8)
  {
    slug: 'gemini',
    name: 'Google Gemini',
    tagline: 'Google\'s most capable AI model',
    description: 'Google Gemini is a multimodal AI that can understand text, images, video, and audio. Advanced reasoning and creative capabilities.',
    category: 'chat',
    website_url: 'https://gemini.google.com',
    affiliate_link: 'https://toolforge.ai/go/gemini',
    logo_url: 'https://cdn.brandfetch.io/google.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$19.99/month',
    features: ['Multimodal', 'Long context', 'Google integration', 'Real-time info', 'Advanced reasoning'],
    tags: ['AI chatbot', 'multimodal', 'Google', 'search integration'],
    rating: 4.6,
    review_count: 9876,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'perplexity',
    name: 'Perplexity AI',
    tagline: 'AI-powered answer engine',
    description: 'Perplexity combines AI with real-time search to provide accurate, cited answers. Perfect for research and factual queries.',
    category: 'chat',
    website_url: 'https://www.perplexity.ai',
    affiliate_link: 'https://toolforge.ai/go/perplexity',
    logo_url: 'https://cdn.brandfetch.io/perplexity.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$20/month',
    features: ['Real-time search', 'Citations', 'Pro search', 'Multiple sources', 'Follow-up questions'],
    tags: ['search', 'research', 'citations', 'factual'],
    rating: 4.7,
    review_count: 6543,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'poe',
    name: 'Poe',
    tagline: 'Access multiple AI chatbots in one place',
    description: 'Poe by Quora gives you access to multiple AI models including GPT-4, Claude, and more. Switch between models seamlessly.',
    category: 'chat',
    website_url: 'https://poe.com',
    affiliate_link: 'https://toolforge.ai/go/poe',
    logo_url: 'https://cdn.brandfetch.io/poe.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$20/month',
    features: ['Multiple AI models', 'Custom bots', 'Model comparison', 'Mobile app', 'Bot creation'],
    tags: ['multi-model', 'chatbot platform', 'comparison', 'Quora'],
    rating: 4.5,
    review_count: 4321,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'character-ai',
    name: 'Character.AI',
    tagline: 'Chat with AI characters and personalities',
    description: 'Character.AI lets you chat with AI characters, from historical figures to fictional personalities. Create your own characters too.',
    category: 'chat',
    website_url: 'https://character.ai',
    affiliate_link: 'https://toolforge.ai/go/character-ai',
    logo_url: 'https://cdn.brandfetch.io/character.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9.99/month',
    features: ['Character chat', 'Create characters', 'Community', 'Voice chat', 'Personality'],
    tags: ['entertainment', 'roleplay', 'characters', 'creative'],
    rating: 4.4,
    review_count: 15432,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'pi-ai',
    name: 'Pi',
    tagline: 'Your personal AI companion',
    description: 'Pi is designed to be a supportive, empathetic AI companion. Great for casual conversation, brainstorming, and personal advice.',
    category: 'chat',
    website_url: 'https://pi.ai',
    affiliate_link: 'https://toolforge.ai/go/pi-ai',
    logo_url: 'https://cdn.brandfetch.io/pi.ai/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Conversational', 'Voice chat', 'Empathetic', 'Personal coach', 'Mobile app'],
    tags: ['personal assistant', 'conversational', 'free', 'friendly'],
    rating: 4.5,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'you-chat',
    name: 'You.com Chat',
    tagline: 'AI chat with real-time web access',
    description: 'You.com\'s AI chat combines conversational AI with web search. Get up-to-date information with citations.',
    category: 'chat',
    website_url: 'https://you.com/chat',
    affiliate_link: 'https://toolforge.ai/go/you-chat',
    logo_url: 'https://cdn.brandfetch.io/you.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$15/month',
    features: ['Web search', 'Citations', 'Multiple modes', 'Privacy focused', 'Current events'],
    tags: ['search', 'web access', 'privacy', 'citations'],
    rating: 4.3,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'huggingchat',
    name: 'HuggingChat',
    tagline: 'Open-source AI chatbot',
    description: 'HuggingChat is an open-source alternative to ChatGPT. Free access to powerful open-source language models.',
    category: 'chat',
    website_url: 'https://huggingface.co/chat',
    affiliate_link: 'https://toolforge.ai/go/huggingchat',
    logo_url: 'https://cdn.brandfetch.io/huggingface.co/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Open source', 'Multiple models', 'Free', 'Privacy', 'Community'],
    tags: ['open source', 'free', 'privacy', 'community'],
    rating: 4.4,
    review_count: 4567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'inflection-pi',
    name: 'Inflection AI',
    tagline: 'Personal intelligence chatbot',
    description: 'Inflection AI powers Pi, offering natural conversation and emotional intelligence. Designed for personal assistance.',
    category: 'chat',
    website_url: 'https://inflection.ai',
    affiliate_link: 'https://toolforge.ai/go/inflection-pi',
    logo_url: 'https://cdn.brandfetch.io/inflection.ai/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Natural conversation', 'Emotional intelligence', 'Personal assistant', 'Voice support', 'Contextual'],
    tags: ['personal AI', 'emotional intelligence', 'conversation', 'free'],
    rating: 4.5,
    review_count: 1876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // PRODUCTIVITY TOOLS (10)
  {
    slug: 'motion',
    name: 'Motion',
    tagline: 'AI-powered calendar and project manager',
    description: 'Motion uses AI to automatically plan your day, schedule tasks, and manage projects. Your intelligent calendar assistant.',
    category: 'productivity',
    website_url: 'https://www.usemotion.com',
    affiliate_link: 'https://toolforge.ai/go/motion',
    logo_url: 'https://cdn.brandfetch.io/usemotion.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$19/month',
    features: ['Auto scheduling', 'Task management', 'Calendar integration', 'Project planning', 'AI prioritization'],
    tags: ['calendar', 'scheduling', 'project management', 'automation'],
    rating: 4.6,
    review_count: 3456,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'otter-ai',
    name: 'Otter.ai',
    tagline: 'AI meeting notes and transcription',
    description: 'Otter.ai records and transcribes meetings in real-time. Get automated summaries, action items, and searchable transcripts.',
    category: 'productivity',
    website_url: 'https://otter.ai',
    affiliate_link: 'https://toolforge.ai/go/otter-ai',
    logo_url: 'https://cdn.brandfetch.io/otter.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$16.99/month',
    features: ['Real-time transcription', 'Meeting summaries', 'Action items', 'Speaker identification', 'Integrations'],
    tags: ['transcription', 'meetings', 'note-taking', 'collaboration'],
    rating: 4.6,
    review_count: 8765,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'fireflies-ai',
    name: 'Fireflies.ai',
    tagline: 'AI meeting assistant and note-taker',
    description: 'Fireflies.ai automatically joins meetings, records, transcribes, and summarizes. Search across all your meetings.',
    category: 'productivity',
    website_url: 'https://fireflies.ai',
    affiliate_link: 'https://toolforge.ai/go/fireflies-ai',
    logo_url: 'https://cdn.brandfetch.io/fireflies.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$10/month',
    features: ['Auto join meetings', 'Transcription', 'Summaries', 'CRM integration', 'Search'],
    tags: ['meeting notes', 'transcription', 'automation', 'CRM'],
    rating: 4.5,
    review_count: 5432,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'reclaim-ai',
    name: 'Reclaim.ai',
    tagline: 'AI scheduling for busy teams',
    description: 'Reclaim.ai intelligently defends your time for important work. Auto-schedules habits, tasks, and meetings optimally.',
    category: 'productivity',
    website_url: 'https://reclaim.ai',
    affiliate_link: 'https://toolforge.ai/go/reclaim-ai',
    logo_url: 'https://cdn.brandfetch.io/reclaim.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8/month',
    features: ['Smart scheduling', 'Habit protection', 'Calendar sync', 'Buffer time', 'Analytics'],
    tags: ['scheduling', 'calendar', 'time management', 'habits'],
    rating: 4.7,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'superhuman',
    name: 'Superhuman',
    tagline: 'AI-powered email experience',
    description: 'Superhuman rebuilds email with AI assistance. Write emails faster, get summaries, and reach inbox zero with keyboard shortcuts.',
    category: 'productivity',
    website_url: 'https://superhuman.com',
    affiliate_link: 'https://toolforge.ai/go/superhuman',
    logo_url: 'https://cdn.brandfetch.io/superhuman.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$30/month',
    features: ['AI writing', 'Email summaries', 'Keyboard shortcuts', 'Read receipts', 'Scheduled send'],
    tags: ['email', 'productivity', 'keyboard shortcuts', 'inbox zero'],
    rating: 4.7,
    review_count: 4321,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'mem',
    name: 'Mem',
    tagline: 'AI-powered workspace for your thoughts',
    description: 'Mem is a self-organizing workspace that uses AI to surface the right information at the right time. Capture and connect ideas.',
    category: 'productivity',
    website_url: 'https://mem.ai',
    affiliate_link: 'https://toolforge.ai/go/mem',
    logo_url: 'https://cdn.brandfetch.io/mem.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$10/month',
    features: ['Self-organizing', 'AI chat', 'Smart search', 'Templates', 'Mobile app'],
    tags: ['note-taking', 'knowledge management', 'AI search', 'PKM'],
    rating: 4.5,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'clockwise',
    name: 'Clockwise',
    tagline: 'AI calendar optimization',
    description: 'Clockwise uses AI to optimize your calendar and create more focus time. Automatically moves meetings to ideal times.',
    category: 'productivity',
    website_url: 'https://www.getclockwise.com',
    affiliate_link: 'https://toolforge.ai/go/clockwise',
    logo_url: 'https://cdn.brandfetch.io/getclockwise.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$6.75/month',
    features: ['Calendar optimization', 'Focus time', 'Meeting scheduling', 'Analytics', 'Team coordination'],
    tags: ['calendar', 'focus time', 'meeting management', 'analytics'],
    rating: 4.6,
    review_count: 2876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'reflect',
    name: 'Reflect',
    tagline: 'AI-enhanced note-taking',
    description: 'Reflect is a networked note-taking app with AI features. Backlinks, daily notes, and AI-powered search and summaries.',
    category: 'productivity',
    website_url: 'https://reflect.app',
    affiliate_link: 'https://toolforge.ai/go/reflect',
    logo_url: 'https://cdn.brandfetch.io/reflect.app/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$10/month',
    features: ['Networked notes', 'AI chat', 'Backlinks', 'Calendar integration', 'End-to-end encryption'],
    tags: ['note-taking', 'knowledge graph', 'backlinks', 'privacy'],
    rating: 4.6,
    review_count: 1876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'tldv',
    name: 'tl;dv',
    tagline: 'AI meeting recorder for Zoom and Google Meet',
    description: 'tl;dv records, transcribes, and summarizes your meetings. Highlight key moments and share insights with your team.',
    category: 'productivity',
    website_url: 'https://tldv.io',
    affiliate_link: 'https://toolforge.ai/go/tldv',
    logo_url: 'https://cdn.brandfetch.io/tldv.io/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$20/month',
    features: ['Meeting recording', 'Transcription', 'Highlights', 'Clips', 'Integrations'],
    tags: ['meeting recording', 'transcription', 'collaboration', 'highlights'],
    rating: 4.7,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'tactiq',
    name: 'Tactiq',
    tagline: 'Real-time transcription for meetings',
    description: 'Tactiq provides real-time transcription for Google Meet, Zoom, and Teams. Get AI summaries and action items instantly.',
    category: 'productivity',
    website_url: 'https://tactiq.io',
    affiliate_link: 'https://toolforge.ai/go/tactiq',
    logo_url: 'https://cdn.brandfetch.io/tactiq.io/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8/month',
    features: ['Live transcription', 'AI summaries', 'Action items', 'Chrome extension', 'Speaker labels'],
    tags: ['transcription', 'meeting notes', 'Chrome extension', 'real-time'],
    rating: 4.5,
    review_count: 4567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // MARKETING TOOLS (8)
  {
    slug: 'adcreative-ai',
    name: 'AdCreative.ai',
    tagline: 'AI-powered ad creative generation',
    description: 'AdCreative.ai generates conversion-focused ad creatives and social media posts. Data-driven designs that perform.',
    category: 'marketing',
    website_url: 'https://www.adcreative.ai',
    affiliate_link: 'https://toolforge.ai/go/adcreative-ai',
    logo_url: 'https://cdn.brandfetch.io/adcreative.ai/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$29/month',
    features: ['Ad generation', 'Conversion focused', 'Multiple formats', 'A/B testing', 'Brand integration'],
    tags: ['advertising', 'ad creative', 'conversion optimization', 'social media'],
    rating: 4.6,
    review_count: 3456,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'brand24',
    name: 'Brand24',
    tagline: 'AI-powered social listening and monitoring',
    description: 'Brand24 tracks mentions of your brand across the web and social media. AI-powered sentiment analysis and competitive insights.',
    category: 'marketing',
    website_url: 'https://brand24.com',
    affiliate_link: 'https://toolforge.ai/go/brand24',
    logo_url: 'https://cdn.brandfetch.io/brand24.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$79/month',
    features: ['Social listening', 'Sentiment analysis', 'Competitor tracking', 'Influencer discovery', 'Reports'],
    tags: ['social listening', 'brand monitoring', 'sentiment analysis', 'reputation'],
    rating: 4.5,
    review_count: 2876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'seventh-sense',
    name: 'Seventh Sense',
    tagline: 'AI email delivery optimization',
    description: 'Seventh Sense optimizes email send times using AI. Increase engagement by sending when each recipient is most likely to interact.',
    category: 'marketing',
    website_url: 'https://theseventhsense.com',
    affiliate_link: 'https://toolforge.ai/go/seventh-sense',
    logo_url: 'https://cdn.brandfetch.io/theseventhsense.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$450/month',
    features: ['Send time optimization', 'Email throttling', 'Engagement prediction', 'HubSpot integration', 'Marketo integration'],
    tags: ['email marketing', 'send time optimization', 'engagement', 'automation'],
    rating: 4.7,
    review_count: 1234,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'persado',
    name: 'Persado',
    tagline: 'AI-powered marketing language generation',
    description: 'Persado uses AI to generate marketing language that resonates emotionally. Optimize copy across emails, ads, and websites.',
    category: 'marketing',
    website_url: 'https://www.persado.com',
    affiliate_link: 'https://toolforge.ai/go/persado',
    logo_url: 'https://cdn.brandfetch.io/persado.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: 'Enterprise',
    features: ['Language generation', 'Emotional targeting', 'A/B testing', 'Multi-channel', 'Enterprise'],
    tags: ['enterprise', 'copywriting', 'email marketing', 'optimization'],
    rating: 4.5,
    review_count: 876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'phrasee',
    name: 'Phrasee',
    tagline: 'AI-optimized marketing language',
    description: 'Phrasee generates and optimizes marketing copy for emails, push notifications, and social media using AI and brand voice.',
    category: 'marketing',
    website_url: 'https://phrasee.co',
    affiliate_link: 'https://toolforge.ai/go/phrasee',
    logo_url: 'https://cdn.brandfetch.io/phrasee.co/w/400/h/400',
    pricing_model: 'paid',
    starting_price: 'Enterprise',
    features: ['Copy optimization', 'Brand voice', 'Multi-channel', 'A/B testing', 'Real-time optimization'],
    tags: ['email marketing', 'copy optimization', 'brand voice', 'enterprise'],
    rating: 4.6,
    review_count: 1123,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'fullstory',
    name: 'FullStory',
    tagline: 'Digital experience analytics with AI',
    description: 'FullStory captures digital experiences and uses AI to uncover insights. Understand user behavior and optimize conversions.',
    category: 'marketing',
    website_url: 'https://www.fullstory.com',
    affiliate_link: 'https://toolforge.ai/go/fullstory',
    logo_url: 'https://cdn.brandfetch.io/fullstory.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: 'Custom',
    features: ['Session replay', 'AI insights', 'Heatmaps', 'Funnel analysis', 'Error tracking'],
    tags: ['analytics', 'user experience', 'session replay', 'conversion optimization'],
    rating: 4.6,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'seventh-sense-hubspot',
    name: 'Pattern89',
    tagline: 'AI for social and search advertising',
    description: 'Pattern89 uses AI to analyze and optimize your social media and search ads. Predictive recommendations for better performance.',
    category: 'marketing',
    website_url: 'https://pattern89.com',
    affiliate_link: 'https://toolforge.ai/go/pattern89',
    logo_url: 'https://cdn.brandfetch.io/pattern89.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$299/month',
    features: ['Ad optimization', 'Creative analysis', 'Predictive insights', 'Multi-platform', 'Performance tracking'],
    tags: ['advertising', 'social ads', 'optimization', 'predictive analytics'],
    rating: 4.5,
    review_count: 1456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'market-brew',
    name: 'MarketBrew',
    tagline: 'AI search engine modeling for SEO',
    description: 'MarketBrew creates AI models of search engines to predict SEO impact. Test changes before implementation.',
    category: 'marketing',
    website_url: 'https://www.marketbrew.ai',
    affiliate_link: 'https://toolforge.ai/go/market-brew',
    logo_url: 'https://cdn.brandfetch.io/marketbrew.ai/w/400/h/400',
    pricing_model: 'paid',
    starting_price: 'Custom',
    features: ['Search engine modeling', 'SEO prediction', 'Competitive analysis', 'Testing', 'Enterprise'],
    tags: ['SEO', 'search engine', 'predictive', 'enterprise'],
    rating: 4.4,
    review_count: 876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // DESIGN TOOLS (8)
  {
    slug: 'uizard',
    name: 'Uizard',
    tagline: 'AI-powered UI design tool',
    description: 'Uizard transforms sketches and text into UI designs. Generate mockups, prototypes, and designs with AI assistance.',
    category: 'design',
    website_url: 'https://uizard.io',
    affiliate_link: 'https://toolforge.ai/go/uizard',
    logo_url: 'https://cdn.brandfetch.io/uizard.io/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$12/month',
    features: ['Text to design', 'Screenshot to design', 'Design assistant', 'Templates', 'Collaboration'],
    tags: ['UI design', 'prototyping', 'wireframes', 'mockups'],
    rating: 4.5,
    review_count: 2345,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'galileo-ai',
    name: 'Galileo AI',
    tagline: 'AI-powered interface design',
    description: 'Galileo AI generates UI designs from text descriptions. Create high-fidelity designs instantly for web and mobile.',
    category: 'design',
    website_url: 'https://www.usegalileo.ai',
    affiliate_link: 'https://toolforge.ai/go/galileo-ai',
    logo_url: 'https://cdn.brandfetch.io/usegalileo.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$19/month',
    features: ['Text to UI', 'High fidelity', 'Mobile & web', 'Figma export', 'AI editing'],
    tags: ['UI design', 'text-to-design', 'Figma', 'high fidelity'],
    rating: 4.6,
    review_count: 1876,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'designify',
    name: 'Designify',
    tagline: 'AI-powered image editing and enhancement',
    description: 'Designify automatically removes backgrounds, enhances colors, and adds shadows. Professional product photos in seconds.',
    category: 'design',
    website_url: 'https://www.designify.com',
    affiliate_link: 'https://toolforge.ai/go/designify',
    logo_url: 'https://cdn.brandfetch.io/designify.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9/month',
    features: ['Background removal', 'Auto enhance', 'Shadow generation', 'Batch processing', 'API access'],
    tags: ['image editing', 'background removal', 'product photos', 'e-commerce'],
    rating: 4.5,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'remove-bg',
    name: 'Remove.bg',
    tagline: 'AI background removal in seconds',
    description: 'Remove.bg uses AI to automatically remove backgrounds from images. Perfect for product photos, portraits, and graphics.',
    category: 'design',
    website_url: 'https://www.remove.bg',
    affiliate_link: 'https://toolforge.ai/go/remove-bg',
    logo_url: 'https://cdn.brandfetch.io/remove.bg/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9/month',
    features: ['Instant removal', 'High quality', 'API', 'Batch processing', 'Plugins'],
    tags: ['background removal', 'image editing', 'automation', 'API'],
    rating: 4.7,
    review_count: 12345,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'khroma',
    name: 'Khroma',
    tagline: 'AI color palette generator',
    description: 'Khroma uses AI to generate color palettes based on your preferences. Train the algorithm and discover personalized color combinations.',
    category: 'design',
    website_url: 'https://www.khroma.co',
    affiliate_link: 'https://toolforge.ai/go/khroma',
    logo_url: 'https://cdn.brandfetch.io/khroma.co/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['AI training', 'Infinite palettes', 'Search', 'Save favorites', 'Typography pairing'],
    tags: ['color palettes', 'design', 'personalized', 'free'],
    rating: 4.6,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'fontjoy',
    name: 'Fontjoy',
    tagline: 'AI font pairing generator',
    description: 'Fontjoy uses deep learning to generate font pairings. Balance and contrast options to find the perfect combination.',
    category: 'design',
    website_url: 'https://fontjoy.com',
    affiliate_link: 'https://toolforge.ai/go/fontjoy',
    logo_url: 'https://cdn.brandfetch.io/fontjoy.com/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Font pairing', 'Balance control', 'Lock fonts', 'Google Fonts', 'Free'],
    tags: ['typography', 'fonts', 'design', 'free'],
    rating: 4.5,
    review_count: 1876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'logo-ai',
    name: 'Looka',
    tagline: 'AI-powered logo maker',
    description: 'Looka uses AI to generate custom logos based on your preferences. Get a complete brand kit with business cards and social templates.',
    category: 'design',
    website_url: 'https://looka.com',
    affiliate_link: 'https://toolforge.ai/go/looka',
    logo_url: 'https://cdn.brandfetch.io/looka.com/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$20 (one-time)',
    features: ['Logo generation', 'Brand kit', 'Business cards', 'Social templates', 'Mockups'],
    tags: ['logo design', 'branding', 'business', 'templates'],
    rating: 4.5,
    review_count: 8765,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'autodraw',
    name: 'AutoDraw',
    tagline: 'AI-assisted drawing by Google',
    description: 'AutoDraw by Google uses machine learning to recognize your sketches and suggest professional drawings. Fast, fun, and free.',
    category: 'design',
    website_url: 'https://www.autodraw.com',
    affiliate_link: 'https://toolforge.ai/go/autodraw',
    logo_url: 'https://cdn.brandfetch.io/autodraw.com/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Sketch recognition', 'Professional drawings', 'Free', 'Easy to use', 'Google'],
    tags: ['drawing', 'sketching', 'free', 'Google', 'simple'],
    rating: 4.3,
    review_count: 4567,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // AUDIO TOOLS (8)
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    tagline: 'AI voice generator and text-to-speech',
    description: 'ElevenLabs creates the most realistic AI voices. Text-to-speech, voice cloning, and dubbing with emotional range.',
    category: 'audio',
    website_url: 'https://elevenlabs.io',
    affiliate_link: 'https://toolforge.ai/go/elevenlabs',
    logo_url: 'https://cdn.brandfetch.io/elevenlabs.io/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$5/month',
    features: ['Text-to-speech', 'Voice cloning', 'Dubbing', 'Multiple languages', 'API access'],
    tags: ['voice generation', 'TTS', 'voice cloning', 'dubbing'],
    rating: 4.8,
    review_count: 9876,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'murf-ai',
    name: 'Murf AI',
    tagline: 'AI voice generator for professional use',
    description: 'Murf AI offers studio-quality AI voices for videos, presentations, and e-learning. Natural-sounding with fine-grained control.',
    category: 'audio',
    website_url: 'https://murf.ai',
    affiliate_link: 'https://toolforge.ai/go/murf-ai',
    logo_url: 'https://cdn.brandfetch.io/murf.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$19/month',
    features: ['120+ voices', 'Voice cloning', 'Video editor', 'Collaboration', 'Commercial use'],
    tags: ['voice generation', 'TTS', 'professional', 'e-learning'],
    rating: 4.6,
    review_count: 5432,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'speechify',
    name: 'Speechify',
    tagline: 'AI text-to-speech for listening',
    description: 'Speechify converts text to natural-sounding audio. Listen to articles, PDFs, and documents on the go.',
    category: 'audio',
    website_url: 'https://speechify.com',
    affiliate_link: 'https://toolforge.ai/go/speechify',
    logo_url: 'https://cdn.brandfetch.io/speechify.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$11.58/month',
    features: ['Natural voices', 'Speed control', 'Multi-platform', 'OCR', 'Offline listening'],
    tags: ['text-to-speech', 'accessibility', 'reading', 'productivity'],
    rating: 4.5,
    review_count: 23456,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'play-ht',
    name: 'Play.ht',
    tagline: 'AI voice generation and cloning',
    description: 'Play.ht offers ultra-realistic AI text-to-speech and voice cloning. Create voiceovers for videos, audiobooks, and more.',
    category: 'audio',
    website_url: 'https://play.ht',
    affiliate_link: 'https://toolforge.ai/go/play-ht',
    logo_url: 'https://cdn.brandfetch.io/play.ht/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$19/month',
    features: ['Voice cloning', '800+ voices', 'Multilingual', 'Audio editor', 'API'],
    tags: ['TTS', 'voice cloning', 'audiobooks', 'voiceover'],
    rating: 4.6,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'resemble-ai',
    name: 'Resemble AI',
    tagline: 'AI voice generator for developers',
    description: 'Resemble AI offers AI voice generation with focus on custom voices and real-time generation. Built for developers and enterprise.',
    category: 'audio',
    website_url: 'https://www.resemble.ai',
    affiliate_link: 'https://toolforge.ai/go/resemble-ai',
    logo_url: 'https://cdn.brandfetch.io/resemble.ai/w/400/h/400',
    pricing_model: 'paid',
    starting_price: '$0.006/second',
    features: ['Custom voices', 'Real-time', 'API-first', 'Voice cloning', 'Localization'],
    tags: ['voice generation', 'API', 'enterprise', 'real-time'],
    rating: 4.5,
    review_count: 1876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'suno-ai',
    name: 'Suno',
    tagline: 'AI music generation from text',
    description: 'Suno creates complete songs from text prompts. Generate music in any style with vocals and instruments.',
    category: 'audio',
    website_url: 'https://www.suno.ai',
    affiliate_link: 'https://toolforge.ai/go/suno-ai',
    logo_url: 'https://cdn.brandfetch.io/suno.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8/month',
    features: ['Text to music', 'Vocals included', 'Multiple genres', 'Commercial use', 'High quality'],
    tags: ['music generation', 'AI music', 'text-to-music', 'creative'],
    rating: 4.7,
    review_count: 6543,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'aiva',
    name: 'AIVA',
    tagline: 'AI music composition',
    description: 'AIVA composes emotional soundtrack music for your projects. Used by content creators, game developers, and filmmakers.',
    category: 'audio',
    website_url: 'https://www.aiva.ai',
    affiliate_link: 'https://toolforge.ai/go/aiva',
    logo_url: 'https://cdn.brandfetch.io/aiva.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$11/month',
    features: ['Soundtrack generation', 'Genre variety', 'Customizable', 'Commercial use', 'MIDI download'],
    tags: ['music composition', 'soundtrack', 'royalty-free', 'game music'],
    rating: 4.4,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'mubert',
    name: 'Mubert',
    tagline: 'AI-generated royalty-free music',
    description: 'Mubert generates unique, royalty-free music streams and tracks. Perfect for content creators, streamers, and apps.',
    category: 'audio',
    website_url: 'https://mubert.com',
    affiliate_link: 'https://toolforge.ai/go/mubert',
    logo_url: 'https://cdn.brandfetch.io/mubert.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$14/month',
    features: ['Royalty-free', 'Infinite music', 'Multiple moods', 'API', 'Content creation'],
    tags: ['royalty-free music', 'background music', 'streaming', 'content creation'],
    rating: 4.3,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },

  // RESEARCH TOOLS (8)
  {
    slug: 'consensus',
    name: 'Consensus',
    tagline: 'AI-powered research engine',
    description: 'Consensus uses AI to search and summarize scientific research papers. Get evidence-based answers backed by peer-reviewed studies.',
    category: 'research',
    website_url: 'https://consensus.app',
    affiliate_link: 'https://toolforge.ai/go/consensus',
    logo_url: 'https://cdn.brandfetch.io/consensus.app/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$8.99/month',
    features: ['Research search', 'Paper summaries', 'Citations', 'Evidence-based', 'Academic'],
    tags: ['research', 'academic', 'scientific papers', 'evidence-based'],
    rating: 4.7,
    review_count: 4321,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'elicit',
    name: 'Elicit',
    tagline: 'AI research assistant',
    description: 'Elicit helps you find, understand, and summarize research papers. AI-powered literature review and data extraction.',
    category: 'research',
    website_url: 'https://elicit.org',
    affiliate_link: 'https://toolforge.ai/go/elicit',
    logo_url: 'https://cdn.brandfetch.io/elicit.org/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$10/month',
    features: ['Paper search', 'Summaries', 'Data extraction', 'Citations', 'Workflow'],
    tags: ['research', 'literature review', 'academic', 'data extraction'],
    rating: 4.6,
    review_count: 3456,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'scite',
    name: 'Scite',
    tagline: 'Smart citations for research',
    description: 'Scite shows how research papers have been cited, indicating if citations support or contradict the research. Critical analysis tool.',
    category: 'research',
    website_url: 'https://scite.ai',
    affiliate_link: 'https://toolforge.ai/go/scite',
    logo_url: 'https://cdn.brandfetch.io/scite.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9.99/month',
    features: ['Smart citations', 'Support/contradict', 'Dashboard', 'Reference check', 'Browser extension'],
    tags: ['citations', 'research', 'academic', 'critical analysis'],
    rating: 4.5,
    review_count: 2345,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'scholarcy',
    name: 'Scholarcy',
    tagline: 'AI article summarizer for research',
    description: 'Scholarcy reads research articles and creates summary flashcards. Extract key information, tables, and figures automatically.',
    category: 'research',
    website_url: 'https://www.scholarcy.com',
    affiliate_link: 'https://toolforge.ai/go/scholarcy',
    logo_url: 'https://cdn.brandfetch.io/scholarcy.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$4.99/month',
    features: ['Article summaries', 'Flashcards', 'Key findings', 'Reference extraction', 'Browser extension'],
    tags: ['research', 'summarization', 'academic', 'flashcards'],
    rating: 4.4,
    review_count: 1876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'semantic-scholar',
    name: 'Semantic Scholar',
    tagline: 'AI-powered academic search',
    description: 'Semantic Scholar uses AI to help researchers discover and understand scientific literature. Free access to millions of papers.',
    category: 'research',
    website_url: 'https://www.semanticscholar.org',
    affiliate_link: 'https://toolforge.ai/go/semantic-scholar',
    logo_url: 'https://cdn.brandfetch.io/semanticscholar.org/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Paper search', 'AI summaries', 'Citation context', 'Free', 'Comprehensive'],
    tags: ['academic search', 'research', 'free', 'citations'],
    rating: 4.6,
    review_count: 5678,
    is_featured: true,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'iris-ai',
    name: 'Iris.ai',
    tagline: 'AI for scientific research',
    description: 'Iris.ai helps researchers find relevant papers and extract insights. AI-powered research assistant for literature review.',
    category: 'research',
    website_url: 'https://iris.ai',
    affiliate_link: 'https://toolforge.ai/go/iris-ai',
    logo_url: 'https://cdn.brandfetch.io/iris.ai/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$9/month',
    features: ['Paper discovery', 'Topic mapping', 'Concept search', 'Literature review', 'Workspace'],
    tags: ['research', 'literature review', 'paper discovery', 'scientific'],
    rating: 4.4,
    review_count: 1456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'research-rabbit',
    name: 'ResearchRabbit',
    tagline: 'Discover connected research papers',
    description: 'ResearchRabbit visualizes connections between research papers. Discover new papers based on citations and topics.',
    category: 'research',
    website_url: 'https://www.researchrabbit.ai',
    affiliate_link: 'https://toolforge.ai/go/research-rabbit',
    logo_url: 'https://cdn.brandfetch.io/researchrabbit.ai/w/400/h/400',
    pricing_model: 'free',
    starting_price: 'Free',
    features: ['Paper discovery', 'Citation network', 'Collections', 'Collaboration', 'Alerts'],
    tags: ['research', 'paper discovery', 'citations', 'free', 'visualization'],
    rating: 4.7,
    review_count: 2876,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
  {
    slug: 'connected-papers',
    name: 'Connected Papers',
    tagline: 'Explore academic papers visually',
    description: 'Connected Papers creates visual graphs of research papers. Find related work and understand research landscape at a glance.',
    category: 'research',
    website_url: 'https://www.connectedpapers.com',
    affiliate_link: 'https://toolforge.ai/go/connected-papers',
    logo_url: 'https://cdn.brandfetch.io/connectedpapers.com/w/400/h/400',
    pricing_model: 'freemium',
    starting_price: '$6/month',
    features: ['Visual graphs', 'Paper discovery', 'Prior work', 'Derivative work', 'Timeline'],
    tags: ['research', 'visualization', 'paper discovery', 'citations'],
    rating: 4.6,
    review_count: 3456,
    is_featured: false,
    status: 'published',
    published_at: new Date().toISOString(),
  },
];

async function seedTools() {
  console.log('Starting tool seeding...');
  console.log(`Preparing to seed ${tools.length} tools`);

  let successCount = 0;
  let errorCount = 0;

  for (const tool of tools) {
    try {
      // Check if tool already exists
      const { data: existing } = await supabase
        .from('tools')
        .select('id')
        .eq('slug', tool.slug)
        .single();

      if (existing) {
        console.log(`⏭️  Skipping ${tool.name} (already exists)`);
        continue;
      }

      // Insert tool
      const { error } = await supabase
        .from('tools')
        .insert([tool]);

      if (error) throw error;

      console.log(`✅ Seeded: ${tool.name} (${tool.category})`);
      successCount++;
    } catch (error) {
      console.error(`❌ Error seeding ${tool.name}:`, error);
      errorCount++;
    }
  }

  console.log(`\n✅ Seeding complete!`);
  console.log(`   - Success: ${successCount} tools`);
  console.log(`   - Errors: ${errorCount} tools`);
  console.log(`   - Total: ${tools.length} tools`);

  // Update category tool counts
  console.log('\nUpdating category counts...');
  const categories = ['writing', 'image', 'video', 'code', 'chat', 'productivity', 'marketing', 'design', 'audio', 'research'];

  for (const category of categories) {
    const { count } = await supabase
      .from('tools')
      .select('*', { count: 'exact', head: true })
      .eq('category', category)
      .eq('status', 'published');

    await supabase
      .from('categories')
      .update({ tool_count: count || 0 })
      .eq('slug', category);

    console.log(`📊 ${category}: ${count || 0} tools`);
  }

  console.log('\n🎉 All done!');
}

// Run the seeder
seedTools().catch(console.error);
